
＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2021-03-16 09:16:24,945                                   
【执行时间】[13176]毫秒                                   
【错误位置】System.String 属性[(null)]                                   
【错误描述】出现未知异常                                   
【错误详情】
System.Data.SqlClient.SqlException (0x80131904): The DELETE permission was denied on the object 'ScanningCheckTmp', database 'PDB', schema 'dbo'.
   at SqlSugar.AdoProvider.ExecuteCommandAsync(String sql, SugarParameter[] parameters)
   at SqlSugar.DeleteableProvider`1.ExecuteCommandAsync()
   at WeChat.Core.Repository.BASE.BaseRepository`1.Deleteable(Expression`1 whereExpression) in F:\GitHub\LZ.WeChat.CoreAPI\src\WeChat.Core.Repository\BASE\BaseRepository.cs:line 96
   at WeChat.Core.Service.BASE.BaseService`1.Deleteable(Expression`1 whereExpression) in F:\GitHub\LZ.WeChat.CoreAPI\src\WeChat.Core.Service\BASE\BaseService.cs:line 93
   at WeChat.Core.Api.Controllers.DepotController.Get(String appid, String sign, String nonce, String timespan) in F:\GitHub\LZ.WeChat.CoreAPI\src\WeChat.Core.Api\Controllers\DepotController.cs:line 363
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
ClientConnectionId:1004e0a5-95eb-41ce-93a3-0ac5f8f0e1c9
Error Number:229,State:5,Class:14

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2021-03-16 09:22:06,292                                   
【执行时间】[354524]毫秒                                   
【错误位置】System.String 属性[(null)]                                   
【错误描述】出现未知异常                                   
【错误详情】
System.Data.SqlClient.SqlException (0x80131904): The DELETE permission was denied on the object 'ScanningCheckTmp', database 'PDB', schema 'dbo'.
   at SqlSugar.AdoProvider.ExecuteCommandAsync(String sql, SugarParameter[] parameters)
   at SqlSugar.DeleteableProvider`1.ExecuteCommandAsync()
   at WeChat.Core.Repository.BASE.BaseRepository`1.Deleteable(Expression`1 whereExpression) in F:\GitHub\LZ.WeChat.CoreAPI\src\WeChat.Core.Repository\BASE\BaseRepository.cs:line 96
   at WeChat.Core.Service.BASE.BaseService`1.Deleteable(Expression`1 whereExpression) in F:\GitHub\LZ.WeChat.CoreAPI\src\WeChat.Core.Service\BASE\BaseService.cs:line 93
   at WeChat.Core.Api.Controllers.DepotController.Get(String appid, String sign, String nonce, String timespan) in F:\GitHub\LZ.WeChat.CoreAPI\src\WeChat.Core.Api\Controllers\DepotController.cs:line 363
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
ClientConnectionId:1004e0a5-95eb-41ce-93a3-0ac5f8f0e1c9
Error Number:229,State:5,Class:14

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2021-03-16 09:22:15,070                                   
【执行时间】[363301]毫秒                                   
【错误位置】System.String 属性[(null)]                                   
【错误描述】出现未知异常                                   
【错误详情】
System.Data.SqlClient.SqlException (0x80131904): The DELETE permission was denied on the object 'ScanningCheckTmp', database 'PDB', schema 'dbo'.
   at SqlSugar.AdoProvider.ExecuteCommandAsync(String sql, SugarParameter[] parameters)
   at SqlSugar.DeleteableProvider`1.ExecuteCommandAsync()
   at WeChat.Core.Repository.BASE.BaseRepository`1.Deleteable(Expression`1 whereExpression) in F:\GitHub\LZ.WeChat.CoreAPI\src\WeChat.Core.Repository\BASE\BaseRepository.cs:line 96
   at WeChat.Core.Service.BASE.BaseService`1.Deleteable(Expression`1 whereExpression) in F:\GitHub\LZ.WeChat.CoreAPI\src\WeChat.Core.Service\BASE\BaseService.cs:line 93
   at WeChat.Core.Api.Controllers.DepotController.Get(String appid, String sign, String nonce, String timespan) in F:\GitHub\LZ.WeChat.CoreAPI\src\WeChat.Core.Api\Controllers\DepotController.cs:line 363
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
ClientConnectionId:a88fa4ab-1aeb-418a-931b-df4cb0e0c69d
Error Number:229,State:5,Class:14

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2021-03-16 13:39:39,388                                   
【执行时间】[22660]毫秒                                   
【错误位置】System.String 属性[(null)]                                   
【错误描述】出现未知异常                                   
【错误详情】
System.Data.SqlClient.SqlException (0x80131904): Cannot find the object "ScanningCheckTmp" because it does not exist or you do not have permissions.
   at SqlSugar.AdoProvider.ExecuteCommandAsync(String sql, SugarParameter[] parameters)
   at WeChat.Core.Repository.BASE.BaseRepository`1.SqlCommand(String sql) in F:\GitHub\LZ.WeChat.CoreAPI\src\WeChat.Core.Repository\BASE\BaseRepository.cs:line 22
   at WeChat.Core.Api.Controllers.DepotController.Get(String appid, String sign, String nonce, String timespan) in F:\GitHub\LZ.WeChat.CoreAPI\src\WeChat.Core.Api\Controllers\DepotController.cs:line 369
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
ClientConnectionId:893f0458-a3c6-4c8b-8897-8e82ee31346f
Error Number:1088,State:7,Class:16

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2021-03-16 13:41:27,883                                   
【执行时间】[23160]毫秒                                   
【错误位置】System.String 属性[(null)]                                   
【错误描述】出现未知异常                                   
【错误详情】
System.Data.SqlClient.SqlException (0x80131904): Cannot find the object "ScanningCheckTmp" because it does not exist or you do not have permissions.
   at SqlSugar.AdoProvider.ExecuteCommandAsync(String sql, SugarParameter[] parameters)
   at WeChat.Core.Repository.BASE.BaseRepository`1.SqlCommand(String sql) in F:\GitHub\LZ.WeChat.CoreAPI\src\WeChat.Core.Repository\BASE\BaseRepository.cs:line 22
   at WeChat.Core.Api.Controllers.DepotController.Get(String appid, String sign, String nonce, String timespan) in F:\GitHub\LZ.WeChat.CoreAPI\src\WeChat.Core.Api\Controllers\DepotController.cs:line 369
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
ClientConnectionId:30c12771-eb2e-4a52-8e50-8208f98e2e8e
Error Number:1088,State:7,Class:16

＝＝＝＝＝＝＝＝＝＝                                   
【日志级别】ERROR                                   
【记录时间】2021-03-16 13:41:51,007                                   
【执行时间】[46284]毫秒                                   
【错误位置】System.String 属性[(null)]                                   
【错误描述】出现未知异常                                   
【错误详情】
System.Data.SqlClient.SqlException (0x80131904): Cannot find the object "ScanningCheckTmp" because it does not exist or you do not have permissions.
   at SqlSugar.AdoProvider.ExecuteCommandAsync(String sql, SugarParameter[] parameters)
   at WeChat.Core.Repository.BASE.BaseRepository`1.SqlCommand(String sql) in F:\GitHub\LZ.WeChat.CoreAPI\src\WeChat.Core.Repository\BASE\BaseRepository.cs:line 22
   at WeChat.Core.Api.Controllers.DepotController.Get(String appid, String sign, String nonce, String timespan) in F:\GitHub\LZ.WeChat.CoreAPI\src\WeChat.Core.Api\Controllers\DepotController.cs:line 369
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
ClientConnectionId:30c12771-eb2e-4a52-8e50-8208f98e2e8e
Error Number:1088,State:7,Class:16
